### ISSUE TITLE
ros_book installation issue

### ISSUE THREAD

**Issue by amiltonwong** [AaronMR/ROS_Book_Hydro#12]
Hi, @AaronMR ,

My system is ubuntu 12.04 and ROS hydro installed.
I followed your steps from readme
But came across the following issue after "wstool up -j8"
# 

root@milton-OptiPlex-760:~/dev/catkin_ws/src# wstool up -j8
[ros_book] still active
[ros_book] Fetching git@github.com:AaronMR/Learning_ROS_for_Robotics_Programming_2nd_edition.git (version None) to /root/dev/catkin_ws/src/ros_book
Cloning into '/root/dev/catkin_ws/src/ros_book'...
[ros_book] still active
[ros_book] still active
[ros_book] still active
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
Exception caught during install: Error processing 'ros_book' : [ros_book] Checkout of git@github.com:AaronMR/Learning_ROS_for_Robotics_Programming_2nd_edition.git version None into /root/dev/catkin_ws/src/ros_book failed.

ERROR in config: Error processing 'ros_book' : [ros_book] Checkout of git@github.com:AaronMR/Learning_ROS_for_Robotics_Programming_2nd_edition.git version None into /root/dev/catkin_ws/src/ros_book failed.
# 

Any idea to fix it?

Thanks in advance~
Milton

**Comment by efernandez** [comment]
You have to setup your ssh keys for github properly: https://help.github.com/articles/generating-ssh-keys/

Or you can use https protocol instead of git, that is, use
`https://github.com/AaronMR/Learning_ROS_for_Robotics_Programming_2nd_edition.git`
instead of
`git@github.com:AaronMR/Learning_ROS_for_Robotics_Programming_2nd_edition.git`
